### ISSUE TITLE
I am not sure why I am getting an error here.

### ISSUE THREAD

**Issue by WeakJames1** [AUPE-Programmers/Homework#8]
![2020-08-03 (5)](https://user-images.githubusercontent.com/68130410/89250871-b63d8900-d5e3-11ea-99e7-6a5c1c7e21d8.png)

**Comment by lawrenberg** [comment]
You are getting an error because you don't have a method called
"continue()" or "stop()" in the class.  I mentioned in the lesson, don't
worry about those because we will eventually get to those concepts.  They
are just *examples*.   Use the topics we went over, which includes:
- https://github.com/AUPE-Programmers/Homework/projects/1#card-41248225
- Logic and Logic Operations.

**Comment by lawrenberg** [comment]
Also, read the entire homework first before you start coding so you get an idea of what is going on before you start coding.  Trying to take a line at a time doesn't give you a full picture.  Reading the entire thing first will give you a bigger picture before you attempt at writing a solution.

**Comment by GodSpeed175** [comment]
In the beginning "##Exercise 1: Translate Logic Expression to Java Code codename". Do we have to do it in Gitpod?

**Comment by lawrenberg** [comment]
Always in Gitpod @GodSpeed175.   However, if you set your computer up to work then you can do it there as well.

**Comment by GodSpeed175** [comment]
Ms I don't understand why I have an error
![2020-08-04 (15)](https://user-images.githubusercontent.com/67125132/89355336-1f2b0c80-d689-11ea-8ea6-4dc9667ccb80.png)

**Comment by lawrenberg** [comment]
@GodSpeed175 you have too many parentheses on Line 7.
